Repository storyblok/storyblok-react, pull requests merged in 2024-12, with the labels that each got.

#1283 feat: add `StoryblokRichText` component and `useStoryblokRichText` hook
  README.md
  playground/next15/src/app/page.tsx
  playground/next15/src/components/IFrameEmbed.tsx
  playground/next15/src/lib/storyblok.ts
  playground/react/components/iframe-embed.tsx
  playground/react/index.tsx
  playground/react/tsconfig.json
  playground/react/tsconfig.node.json
  src/__tests__/richtext.test.ts
  src/common/index.ts
  src/index.ts
  src/richtext.ts
  src/rsc/index.ts
  src/storyblok-rich-text.tsx
  src/types.ts
  src/utils.ts
Labels: p3-significant, feature

#1292 chore: manually bump package.json version to latest release
  package.json
Labels: p1-chore

#1296 fix: allow custom props in StoryblokComponent, Story, and ServerComponent types
  src/__tests__/testing-components/TestUseStoryblok.tsx
  src/common/storyblok-component.tsx
  src/rsc/server-component.tsx
  src/rsc/story.tsx
Labels: bugfix, p3-significant

#1299 chore: increment commit body max size to allow dependabot commits
  package.json
Labels: p1-chore

#1293 chore: change from auto-merge to auto-approve and upgrade dependabot action
  .github/dependabot.yml
  .github/workflows/dependabot-automerge.yml
Labels: p1-chore

#1303 fix: resolve path aliases in d.ts build files
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: bug
